name: remote ssh command
on: [push]

jobs:

  testing01:
    name: deploying
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: multiple ssh commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
            cd ~/graphologue
            pm2 stop graphologue
            pm2 delete graphologue
            rm -rf node_modules package-lock.json
            git pull origin public
            git status
            npm install
            pm2 start npm --name 'graphologue' -- start